services:
  - type: web
    name: transliteration-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    healthCheckPath: /
    # --- ADD THIS SECTION ---
    healthCheckInitialDelaySeconds: 300 
    # ------------------------
    envVars:
      - key: PORT
        value: 10000